### ISSUE TITLE
New MFE: Learner Dashboard

### ISSUE THREAD

**Issue by arbrandes** [openedx/frontend-app-learner-dashboard#211]
### Description

Make sure this MFE follows all [the community requirements](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3561521275/Requirements+for+an+MFE).  Sub-tasks are listed below.

### Links

* [Related forum thread](https://discuss.openedx.org/t/learners-dashboard-mfe-is-not-ready-for-usage-in-community/10697)

### Sub-tasks

- [ ] https://github.com/openedx/frontend-app-learner-dashboard/issues/176
- [ ] https://github.com/openedx/frontend-app-learner-dashboard/issues/178
- [ ] https://github.com/openedx/frontend-app-learner-dashboard/issues/183
- [ ] https://github.com/openedx/frontend-app-learner-dashboard/issues/210
- [ ] Update frontend-platform to 5.5.1+

#### Pre-existing PRs

- [ ] https://github.com/openedx/frontend-app-learner-dashboard/pull/180
- [ ] https://github.com/openedx/frontend-app-learner-dashboard/pull/205
- [ ] https://github.com/openedx/frontend-app-learner-dashboard/pull/209

**Comment by arbrandes** [comment]
Ug, we already had an issue for it [in the Roadmap](https://github.com/openedx/platform-roadmap/issues/217), and I forgot.  Closing as duplicate.
