### ISSUE TITLE
README to-dos

### ISSUE THREAD

**Issue by httpsmenahassan** [openedx/frontend-app-learner-dashboard#213]
I reviewed this repo's README against [these specifications](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055/decisions/0003-readme-specification.html) and outlined what's currently included and what needs to be added below.

When making any changes or updates, note that ideally we should stick to the exact section order shown below with additional sections added where it makes sense based on the maintainers' judgement.

### Tasks
- [x] Title - The name of the component.
- [ ] Badges - A set of [badges](https://github.com/badges/shields) that quickly let visitors review the health of the project.
- The badges section should contain at minimum the following badges:

1. License - Indicating the license of the repo.
2. Maintenance Status - One of maintained, deprecated, unsupported, experimental.
3. CI Status - The status of CI testing on the main branch.
4. Package Published Status - If the component is a library, then a badge indicating whether publishes to the relevant package index are passing. For example, has the latest version been successfully published to PyPI yor NPM?

- [x] Purpose - A paragraph or two summarizing the purpose of this component. This should be oriented towards people who are new to the Open edX project.
- [ ] Getting Started - A section that details various aspects of getting started with this component. Some common use cases include, getting started with development or how to deploy this component.
PARTIALLY DONE:
1.  Quickstart section doesn’t isn’t include `npm install` or `nvm use`
2. It also doesn’t mention that devstack should be running in the background. Not sure if we need that explicitly listed but if the goal of the README is to be as beginner friendly as possible, it’d be good to have that be clearly stated

- [ ] Getting Help - A section to indicate where and how the user can get help with the component, including how they should go about reporting issues with the component. It should link to relevant docs as well as places where the users can get help from other humans.
- [ ] Contributing - A section to indicate how new users can contribute to this component. This section should at the very least contain a link to the general [How to Contribute](https://openedx.org/r/how-to-contribute) documentation for the Open edX Project.
- [ ] The level of contributions that the maintainer is willing to accept should also be clearly described here. Some possible values might be:
- fixes only - no new features are being accepted at this point, but fixes and maintenance updates welcome.
- new features accepted - please discuss your new ideas with the maintainers before you write code to increase the changes that features are accepted.
- security only - no changes accepted except for security fixes.
- [ ] Open edX Code of Conduct - A section that links to the [Open edX Code of Conduct](https://openedx.org/code-of-conduct/)
- [ ] People - A section that tells people how they can find the current maintainers of this component. Usually a link to the Backstage page for the component.
- [ ] Reporting Security Issues - A link to the e-mail address where security issues can be reported.

**Comment by deborahgu** [comment]
the only 2 things still missing here are the people section, and the level of contributions (which is "new features accepted").
