### ISSUE TITLE
[DEPR]: Upgrade Button

### ISSUE THREAD

**Issue by jsnwesson** [openedx/frontend-app-learner-dashboard#438]
### Proposal Date

2024-08-27

### Target Ticket Acceptance Date

2024-09-10

### Earliest Open edX Named Release Without This Functionality

Sumac - 2024-10

### Rationale

The Upgrade Button has been the most commonly requested component by the Open edX community for removal. As far as we can tell, 2U is the only organization that uses the component, which is why a complete removal of the button is the proposed approach as opposed to making it an optional component that can be injected within a PluginSlot. If the code is indeed unused, it only serves as a liability to the community and should be removed.

### Removal

This is a proposal to remove the [Upgrade Button component](https://github.com/openedx/frontend-app-learner-dashboard/blob/master/src/containers/CourseCard/components/CourseCardActions/UpgradeButton.jsx), its implementation in [CourseCardActions](https://github.com/openedx/frontend-app-learner-dashboard/blob/master/src/containers/CourseCard/components/CourseCardActions/index.jsx), and any [hooks logic](https://github.com/openedx/frontend-app-learner-dashboard/blob/master/src/containers/CourseCard/components/hooks.js) and [tracking events](https://github.com/openedx/frontend-app-learner-dashboard/blob/master/src/tracking/trackers/course.js) that are only related to "upgrading" a course. 

For the sake of removing the Upgrade Button before the Sumac release, this deprecation proposal _doesn't_ include completely removing upgrade-related information from the `LearnerDashboard.Init()` call to the LMS, which also means that the remaining evidence within Learner Dashboard of a course ever being upgradeable would be found in a [redux selector](https://github.com/openedx/frontend-app-learner-dashboard/blob/00129bcee0800abd70bbeab81eb3e8ee34bbb66e/src/data/redux/app/selectors/courseCard.js#L55). If this were to remain, then it would at least give the Maintaining team the time to remove the Upgrade data from the `init`, as any need to call LearnerDashboard.Init() more than once will have a tremendous impact on the performance of the page. 

### Replacement

With these removals, in [CourseCardActions there would be an empty PluginSlot](https://github.com/openedx/frontend-app-learner-dashboard/blob/00129bcee0800abd70bbeab81eb3e8ee34bbb66e/src/containers/CourseCard/components/CourseCardActions/index.jsx#L25) in place of where the Upgrade Component was implemented to allow for the component to be plugged in using Frontend Plugin Framework. This would also allow any other organization to add whatever action components they would like. 

### Additional Info

@jsnwesson 

### Task List

- [] Add PluginSlot in CourseCardActions
- [] Remove Upgrade Button component and implementation in CourseCardActions
- [] Remove tracking events related to course upgrade

**Comment by julianajlk** [comment]
@jsnwesson hello! Is there an associated ticket for this work/which squad is removing it? Purchase squad uses this Upgrade Button and we were not aware of the removal

**Comment by jsnwesson** [comment]
Hi @julianajlk ! This work is to be done by my team (Aperture). To be clear, we'll actually be keeping the Upgrade button for 2U, but it will be stored as a plugin and preserved in [frontend-plugin-learner-dashboard](https://github.com/edx/frontend-plugin-learner-dashboard). It is intended to work exactly as before, but the benefit is that this button doesn't exist out-of-the-box for Learner Dashboard.

**Comment by julianajlk** [comment]
@jsnwesson Great, I misunderstood and assumed we'd need to make changes on our end to accommodate for this change. If you need any testing to be done when this goes out to production, please let us know. Thank you!

**Comment by feanil** [comment]
@jsnwesson is this work done now? I saw that https://github.com/openedx/frontend-app-learner-dashboard/pull/464 has merged, is there anything else left for this DEPR?

**Comment by jsnwesson** [comment]
@feanil there is some work that still needs to be done for this, which involves creating a private plugin that will live in a private 2U-owned repo. Once that's done, we can remove the upgrade button code from the Learner Dashboard repo.

**Comment by jsnwesson** [comment]
Hi @arbrandes ! @MaxFrank13 is working on creating the upgrade button plugin this week. Once it's in working order, we hope to be able to immediately remove the upgrade button code from Learner Dashboard!
